name:                aardvark
version:             0.1.0.0
github:              "githubuser/aardvark"
license:             BSD3
author:              "Eli Most"
maintainer:          "mosteliml@gmail.com"
copyright:           "2018 Eli Most"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/aardvark#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  dependencies:
    - array

executables:
  aardvark-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aardvark
    - optparse-applicative

tests:
  aardvark-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aardvark
    - process
